spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springdb?serverTimezone=UTC
    hikari:
      max-lifetime: 500000
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates/
  resources:
    static-locations: classpath:/static/,file:static/


mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    cache-enabled: true
server:
  port: 8080

